import type { Metadata } from "next";
import { Inter, Cabin_Sketch } from "next/font/google";

import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-secondary",
});

const cabinSketch = Cabin_Sketch({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cabin-sketch",
});

const dogica = localFont({
  src: [
    { path: "../../public/fonts/dogica.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/dogicabold.ttf", weight: "700", style: "normal" },
    { path: "../../public/fonts/dogicapixel.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/dogicapixelbold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-primary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Legamii",
  description: "Generated by Legamii team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${dogica.variable} ${cabinSketch.variable}`}>
      <body className="antialiased" suppressHydrationWarning>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
